In [2]:
import torch

In [6]:
gates = torch.rand(4, 5)
print("----------gates----------") 
print(gates)
_gates = gates
_num_experts = 5
print("----------torch.nonzero(gates)----------")
print(torch.nonzero(gates))
sorted_experts, index_sorted_experts = torch.nonzero(gates).sort(0)
print("----------sorted_experts----------")
print(sorted_experts)
print("----------index_sorted_experts----------")
print(index_sorted_experts)
_, _expert_index = sorted_experts.split(1, dim=1) # indeed, it returns a tuple
print("----------_expert_index----------")
print(_expert_index)
_batch_index = torch.nonzero(gates)[index_sorted_experts[:, 1], 0]
print("----------_batch_index----------")
print(_batch_index)
_part_sizes = (gates > 0).sum(0).tolist()

gates_exp = gates[_batch_index.flatten()]
print("----------gates_exp----------")
print(gates_exp)
_nonzero_gates = torch.gather(gates_exp, 1, _expert_index)
print("----------_nonzero_gates----------")
print(_nonzero_gates)
print(_nonzero_gates.shape)

----------gates----------
tensor([[0.1609, 0.7184, 0.9006, 0.2271, 0.0042],
        [0.5469, 0.2559, 0.7216, 0.6819, 0.8885],
        [0.8779, 0.6254, 0.6617, 0.4380, 0.9189],
        [0.8924, 0.0348, 0.6778, 0.9942, 0.1902]])
----------torch.nonzero(gates)----------
tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4]])
----------sorted_experts----------
tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 2],
        [1, 2],
        [2, 2],
        [2, 2],
        [2, 3],
        [2, 3],
        [2, 3],
        [3, 3],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]])
----------index_sorted_experts----------
tensor([[ 0,  