In [1]:
import torch

In [2]:
gates = torch.rand(4, 5)
print("----------gates----------") 
print(gates)
_gates = gates
_num_experts = 5
print("----------torch.nonzero(gates)----------")
print(torch.nonzero(gates))
sorted_experts, index_sorted_experts = torch.nonzero(gates).sort(0)
print("----------sorted_experts----------")
print(sorted_experts)
print("----------index_sorted_experts----------")
print(index_sorted_experts)
_, _expert_index = sorted_experts.split(1, dim=1) # indeed, it returns a tuple
print("----------sorted_experts.split(1, dim=1)----------")
print(sorted_experts.split(1, dim=1))
print("----------_expert_index----------")
print(_expert_index)
_batch_index = torch.nonzero(gates)[index_sorted_experts[:, 1], 0]
print("----------_batch_index----------")
print(_batch_index)
_part_sizes = (gates > 0).sum(0).tolist()
print("----------_part_sizes--------")
print(_part_sizes)
gates_exp = gates[_batch_index.flatten()]
print("----------gates_exp----------")
print(gates_exp)
_nonzero_gates = torch.gather(gates_exp, 1, _expert_index)
print("----------_nonzero_gates----------")
print(_nonzero_gates)
print(_nonzero_gates.shape)

----------gates----------
tensor([[0.9449, 0.7434, 0.8901, 0.4017, 0.7616],
        [0.7373, 0.8036, 0.6522, 0.5866, 0.7473],
        [0.1037, 0.2090, 0.4357, 0.3569, 0.7746],
        [0.5578, 0.1895, 0.2159, 0.2749, 0.9661]])
----------torch.nonzero(gates)----------
tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4]])
----------sorted_experts----------
tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 2],
        [1, 2],
        [2, 2],
        [2, 2],
        [2, 3],
        [2, 3],
        [2, 3],
        [3, 3],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]])
----------index_sorted_experts----------
tensor([[ 0,  